# Generated by Django 6.0 on 2025-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_active_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_category',
            field=models.CharField(choices=[('SECURITY', 'Security'), ('HOUSEKEEPING', 'Housekeeping'), ('CANTEEN', 'Canteen')], default='SECURITY', max_length=20),
            preserve_default=False,
        ),
    ]
