# Generated by Django 5.2.9 on 2025-12-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='radius_meters',
            field=models.IntegerField(default=100),
        ),
    ]
