# Generated by Django 5.2.9 on 2025-12-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leaverequest_id'),
        ('leaves', '0002_alter_leaverequest_options_alter_leaverequest_user'),
    ]

    operations = [
    ]
