# Generated by Django 5.2.9 on 2025-12-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_id'),
        ('attendance', '0004_alter_attendance_options_attendance_date_and_more'),
    ]

    operations = [
    ]
